export default {
    countries: [
        {abbr: "US", country: "United States of America"},
        {abbr: "DE", country: "Germany"},
        {abbr: "FR", country: "France"},
        {abbr: "ES", country: "Spain"},
        {abbr: "GB", country: "United Kingdom"},
        {abbr: "AD", country: "Andorra"},
        {abbr: "AE", country: "United Arab Emirates"},
        {abbr: "AF", country: "Afghanistan"},
        {abbr: "AG", country: "Antigua and Barbuda"},
        {abbr: "AI", country: "Anguilla"},
        {abbr: "AL", country: "Albania"},
        {abbr: "AM", country: "Armenia"},
        {abbr: "AO", country: "Angola"},
        {abbr: "AQ", country: "Antarctica"},
        {abbr: "AR", country: "Argentina"},
        {abbr: "AS", country: "American Samoa"},
        {abbr: "AT", country: "Austria"},
        {abbr: "AU", country: "Australia"},
        {abbr: "AW", country: "Aruba"},
        {abbr: "AX", country: "Åland Islands"},
        {abbr: "AZ", country: "Azerbaijan"},
        {abbr: "BA", country: "Bosnia and Herzegovina"},
        {abbr: "BB", country: "Barbados"},
        {abbr: "BD", country: "Bangladesh"},
        {abbr: "BE", country: "Belgium"},
        {abbr: "BF", country: "Burkina Faso"},
        {abbr: "BG", country: "Bulgaria"},
        {abbr: "BH", country: "Bahrain"},
        {abbr: "BI", country: "Burundi"},
        {abbr: "BJ", country: "Benin"},
        {abbr: "BL", country: "Saint Barthélemy"},
        {abbr: "BM", country: "Bermuda"},
        {abbr: "BN", country: "Brunei Darussalam"},
        {abbr: "BO", country: "Bolivia (Plurinational State of)"},
        {abbr: "BQ", country: "Bonaire, Sint Eustatius and Saba"},
        {abbr: "BR", country: "Brazil"},
        {abbr: "BS", country: "Bahamas"},
        {abbr: "BT", country: "Bhutan"},
        {abbr: "BV", country: "Bouvet Island"},
        {abbr: "BW", country: "Botswana"},
        {abbr: "BY", country: "Belarus"},
        {abbr: "BZ", country: "Belize"},
        {abbr: "CA", country: "Canada"},
        {abbr: "CC", country: "Cocos (Keeling) Islands"},
        {abbr: "CD", country: "Congo, Democratic Republic of the"},
        {abbr: "CF", country: "Central African Republic"},
        {abbr: "CG", country: "Congo"},
        {abbr: "CH", country: "Switzerland"},
        {abbr: "CI", country: "Côte d'Ivoire"},
        {abbr: "CK", country: "Cook Islands"},
        {abbr: "CL", country: "Chile"},
        {abbr: "CM", country: "Cameroon"},
        {abbr: "CN", country: "China"},
        {abbr: "CO", country: "Colombia"},
        {abbr: "CR", country: "Costa Rica"},
        {abbr: "CU", country: "Cuba"},
        {abbr: "CV", country: "Cabo Verde"},
        {abbr: "CW", country: "Curaçao"},
        {abbr: "CX", country: "Christmas Island"},
        {abbr: "CY", country: "Cyprus"},
        {abbr: "CZ", country: "Czechia"},
        {abbr: "DJ", country: "Djibouti"},
        {abbr: "DK", country: "Denmark"},
        {abbr: "DM", country: "Dominica"},
        {abbr: "DO", country: "Dominican Republic"},
        {abbr: "DZ", country: "Algeria"},
        {abbr: "EC", country: "Ecuador"},
        {abbr: "EE", country: "Estonia"},
        {abbr: "EG", country: "Egypt"},
        {abbr: "EH", country: "Western Sahara"},
        {abbr: "ER", country: "Eritrea"},
        {abbr: "ET", country: "Ethiopia"},
        {abbr: "FI", country: "Finland"},
        {abbr: "FJ", country: "Fiji"},
        {abbr: "FK", country: "Falkland Islands (Malvinas)"},
        {abbr: "FM", country: "Micronesia (Federated States of)"},
        {abbr: "FO", country: "Faroe Islands"},
        {abbr: "GA", country: "Gabon"},
        {abbr: "GD", country: "Grenada"},
        {abbr: "GE", country: "Georgia"},
        {abbr: "GF", country: "French Guiana"},
        {abbr: "GG", country: "Guernsey"},
        {abbr: "GH", country: "Ghana"},
        {abbr: "GI", country: "Gibraltar"},
        {abbr: "GL", country: "Greenland"},
        {abbr: "GM", country: "Gambia"},
        {abbr: "GN", country: "Guinea"},
        {abbr: "GP", country: "Guadeloupe"},
        {abbr: "GQ", country: "Equatorial Guinea"},
        {abbr: "GR", country: "Greece"},
        {abbr: "GS", country: "South Georgia and the South Sandwich Islands"},
        {abbr: "GT", country: "Guatemala"},
        {abbr: "GU", country: "Guam"},
        {abbr: "GW", country: "Guinea-Bissau"},
        {abbr: "GY", country: "Guyana"},
        {abbr: "HK", country: "Hong Kong"},
        {abbr: "HM", country: "Heard Island and McDonald Islands"},
        {abbr: "HN", country: "Honduras"},
        {abbr: "HR", country: "Croatia"},
        {abbr: "HT", country: "Haiti"},
        {abbr: "HU", country: "Hungary"},
        {abbr: "ID", country: "Indonesia"},
        {abbr: "IE", country: "Ireland"},
        {abbr: "IL", country: "Israel"},
        {abbr: "IM", country: "Isle of Man"},
        {abbr: "IN", country: "India"},
        {abbr: "IO", country: "British Indian Ocean Territory"},
        {abbr: "IQ", country: "Iraq"},
        {abbr: "IR", country: "Iran (Islamic Republic of)"},
        {abbr: "IS", country: "Iceland"},
        {abbr: "IT", country: "Italy"},
        {abbr: "JE", country: "Jersey"},
        {abbr: "JM", country: "Jamaica"},
        {abbr: "JO", country: "Jordan"},
        {abbr: "JP", country: "Japan"},
        {abbr: "KE", country: "Kenya"},
        {abbr: "KG", country: "Kyrgyzstan"},
        {abbr: "KH", country: "Cambodia"},
        {abbr: "KI", country: "Kiribati"},
        {abbr: "KM", country: "Comoros"},
        {abbr: "KN", country: "Saint Kitts and Nevis"},
        {abbr: "KP", country: "Korea (Democratic People's Republic of)"},
        {abbr: "KR", country: "Korea, Republic of"},
        {abbr: "KW", country: "Kuwait"},
        {abbr: "KY", country: "Cayman Islands"},
        {abbr: "KZ", country: "Kazakhstan"},
        {abbr: "LA", country: "Lao People's Democratic Republic"},
        {abbr: "LB", country: "Lebanon"},
        {abbr: "LC", country: "Saint Lucia"},
        {abbr: "LI", country: "Liechtenstein"},
        {abbr: "LK", country: "Sri Lanka"},
        {abbr: "LR", country: "Liberia"},
        {abbr: "LS", country: "Lesotho"},
        {abbr: "LT", country: "Lithuania"},
        {abbr: "LU", country: "Luxembourg"},
        {abbr: "LV", country: "Latvia"},
        {abbr: "LY", country: "Libya"},
        {abbr: "MA", country: "Morocco"},
        {abbr: "MC", country: "Monaco"},
        {abbr: "MD", country: "Moldova, Republic of"},
        {abbr: "ME", country: "Montenegro"},
        {abbr: "MF", country: "Saint Martin (French part)"},
        {abbr: "MG", country: "Madagascar"},
        {abbr: "MH", country: "Marshall Islands"},
        {abbr: "MK", country: "North Macedonia"},
        {abbr: "ML", country: "Mali"},
        {abbr: "MM", country: "Myanmar"},
        {abbr: "MN", country: "Mongolia"},
        {abbr: "MO", country: "Macao"},
        {abbr: "MP", country: "Northern Mariana Islands"},
        {abbr: "MQ", country: "Martinique"},
        {abbr: "MR", country: "Mauritania"},
        {abbr: "MS", country: "Montserrat"},
        {abbr: "MT", country: "Malta"},
        {abbr: "MU", country: "Mauritius"},
        {abbr: "MV", country: "Maldives"},
        {abbr: "MW", country: "Malawi"},
        {abbr: "MX", country: "Mexico"},
        {abbr: "MY", country: "Malaysia"},
        {abbr: "MZ", country: "Mozambique"},
        {abbr: "NA", country: "Namibia"},
        {abbr: "NC", country: "New Caledonia"},
        {abbr: "NE", country: "Niger"},
        {abbr: "NF", country: "Norfolk Island"},
        {abbr: "NG", country: "Nigeria"},
        {abbr: "NI", country: "Nicaragua"},
        {abbr: "NL", country: "Netherlands"},
        {abbr: "NO", country: "Norway"},
        {abbr: "NP", country: "Nepal"},
        {abbr: "NR", country: "Nauru"},
        {abbr: "NU", country: "Niue"},
        {abbr: "NZ", country: "New Zealand"},
        {abbr: "OM", country: "Oman"},
        {abbr: "PA", country: "Panama"},
        {abbr: "PE", country: "Peru"},
        {abbr: "PF", country: "French Polynesia"},
        {abbr: "PG", country: "Papua New Guinea"},
        {abbr: "PH", country: "Philippines"},
        {abbr: "PK", country: "Pakistan"},
        {abbr: "PL", country: "Poland"},
        {abbr: "PM", country: "Saint Pierre and Miquelon"},
        {abbr: "PN", country: "Pitcairn"},
        {abbr: "PR", country: "Puerto Rico"},
        {abbr: "PS", country: "Palestine, State of"},
        {abbr: "PT", country: "Portugal"},
        {abbr: "PW", country: "Palau"},
        {abbr: "PY", country: "Paraguay"},
        {abbr: "QA", country: "Qatar"},
        {abbr: "RE", country: "Réunion"},
        {abbr: "RO", country: "Romania"},
        {abbr: "RS", country: "Serbia"},
        {abbr: "RU", country: "Russian Federation"},
        {abbr: "RW", country: "Rwanda"},
        {abbr: "SA", country: "Saudi Arabia"},
        {abbr: "SB", country: "Solomon Islands"},
        {abbr: "SC", country: "Seychelles"},
        {abbr: "SD", country: "Sudan"},
        {abbr: "SE", country: "Sweden"},
        {abbr: "SG", country: "Singapore"},
        {abbr: "SH", country: "Saint Helena, Ascension and Tristan da Cunha"},
        {abbr: "SI", country: "Slovenia"},
        {abbr: "SJ", country: "Svalbard and Jan Mayen"},
        {abbr: "SK", country: "Slovakia"},
        {abbr: "SL", country: "Sierra Leone"},
        {abbr: "SM", country: "San Marino"},
        {abbr: "SN", country: "Senegal"},
        {abbr: "SO", country: "Somalia"},
        {abbr: "SR", country: "Suriname"},
        {abbr: "SS", country: "South Sudan"},
        {abbr: "ST", country: "Sao Tome and Principe"},
        {abbr: "SV", country: "El Salvador"},
        {abbr: "SX", country: "Sint Maarten (Dutch part)"},
        {abbr: "SY", country: "Syrian Arab Republic"},
        {abbr: "SZ", country: "Eswatini"},
        {abbr: "TC", country: "Turks and Caicos Islands"},
        {abbr: "TD", country: "Chad"},
        {abbr: "TF", country: "French Southern Territories"},
        {abbr: "TG", country: "Togo"},
        {abbr: "TH", country: "Thailand"},
        {abbr: "TJ", country: "Tajikistan"},
        {abbr: "TK", country: "Tokelau"},
        {abbr: "TL", country: "Timor-Leste"},
        {abbr: "TM", country: "Turkmenistan"},
        {abbr: "TN", country: "Tunisia"},
        {abbr: "TO", country: "Tonga"},
        {abbr: "TR", country: "Turkey"},
        {abbr: "TT", country: "Trinidad and Tobago"},
        {abbr: "TV", country: "Tuvalu"},
        {abbr: "TW", country: "Taiwan, Province of China"},
        {abbr: "TZ", country: "Tanzania, United Republic of"},
        {abbr: "UA", country: "Ukraine"},
        {abbr: "UG", country: "Uganda"},
        {abbr: "UM", country: "United States Minor Outlying Islands"},
        {abbr: "UY", country: "Uruguay"},
        {abbr: "UZ", country: "Uzbekistan"},
        {abbr: "VA", country: "Holy See"},
        {abbr: "VC", country: "Saint Vincent and the Grenadines"},
        {abbr: "VE", country: "Venezuela (Bolivarian Republic of)"},
        {abbr: "VG", country: "Virgin Islands (British)"},
        {abbr: "VI", country: "Virgin Islands (U.S.)"},
        {abbr: "VN", country: "Viet Nam"},
        {abbr: "VU", country: "Vanuatu"},
        {abbr: "WF", country: "Wallis and Futuna"},
        {abbr: "WS", country: "Samoa"},
        {abbr: "YE", country: "Yemen"},
        {abbr: "YT", country: "Mayotte"},
        {abbr: "ZA", country: "South Africa"},
        {abbr: "ZM", country: "Zambia"},
        {abbr: "ZW", country: "Zimbabwe"},
    ],
    states: {
        US: [
            {value:'Alabama', text: 'Alabama'},
            {value:'Alaska', text: 'Alaska'},
            {value:'Arizona', text: 'Arizona'},
            {value:'Arkansas', text: 'Arkansas'},
            {value:'California', text: 'California'},
            {value:'Colorado', text: 'Colorado'},
            {value:'Connecticut', text: 'Connecticut'},
            {value:'Delaware', text: 'Delaware'},
            {value:'Florida', text: 'Florida'},
            {value:'Georgia', text: 'Georgia'},
            {value:'Hawaii', text: 'Hawaii'},
            {value:'Idaho', text: 'Idaho'},
            {value:'Illinois', text: 'Illinois'},
            {value:'Indiana', text: 'Indiana'},
            {value:'Iowa', text: 'Iowa'},
            {value:'Kansas', text: 'Kansas'},
            {value:'Kentucky', text: 'Kentucky'},
            {value:'Louisiana', text: 'Louisiana'},
            {value:'Maine', text: 'Maine'},
            {value:'Maryland', text: 'Maryland'},
            {value:'Massachusetts', text: 'Massachusetts'},
            {value:'Michigan', text: 'Michigan'},
            {value:'Minnesota', text: 'Minnesota'},
            {value:'Mississippi', text: 'Mississippi'},
            {value:'Missouri', text: 'Missouri'},
            {value:'Montana', text: 'Montana'},
            {value:'Nebraska', text: 'Nebraska'},
            {value:'Nevada', text: 'Nevada'},
            {value:'New Hampshire', text: 'New Hampshire'},
            {value:'New Jersey', text: 'New Jersey'},
            {value:'New Mexico', text: 'New Mexico'},
            {value:'New York', text: 'New York'},
            {value:'North Carolina', text: 'North Carolina'},
            {value:'North Dakota', text: 'North Dakota'},
            {value:'Ohio', text: 'Ohio'},
            {value:'Oklahoma', text: 'Oklahoma'},
            {value:'Oregon', text: 'Oregon'},
            {value:'Pennsylvania', text: 'Pennsylvania'},
            {value:'Rhode Island', text: 'Rhode Island'},
            {value:'South Carolina', text: 'South Carolina'},
            {value:'South Dakota', text: 'South Dakota'},
            {value:'Tennessee', text: 'Tennessee'},
            {value:'Texas', text: 'Texas'},
            {value:'Utah', text: 'Utah'},
            {value:'Vermont', text: 'Vermont'},
            {value:'Virginia', text: 'Virginia'},
            {value:'Washington', text: 'Washington'},
            {value:'West Virginia', text: 'West Virginia'},
            {value:'Wisconsin', text: 'Wisconsin'},
            {value:'Wyoming', text: 'Wyoming'},
        ],
        CN: [
            {value:"安徽省", text:"安徽省 - Anhui Sheng"},
            {value:"澳门", text:"澳门 - Macau"},
            {value:"北京市", text:"北京市 - Beijing Shi"},
            {value:"重庆市", text:"重庆市 - Chongqing Shi"},
            {value:"福建省", text:"福建省 - Fujian Sheng"},
            {value:"甘肃省", text:"甘肃省 - Gansu Sheng"},
            {value:"广东省", text:"广东省 - Guangdong Sheng"},
            {value:"广西壮族自治区", text:"广西 - Guangxi Zhuangzuzizhiqu"},
            {value:"贵州省", text:"贵州省 - Guizhou Sheng"},
            {value:"海南省", text:"海南省 - Hainan Sheng"},
            {value:"河北省", text:"河北省 - Hebei Sheng"},
            {value:"河南省", text:"河南省 - Henan Sheng"},
            {value:"黑龙江省", text:"黑龙江省 - Heilongjiang Sheng"},
            {value:"湖北省", text:"湖北省 - Hubei Sheng"},
            {value:"湖南省", text:"湖南省 - Hunan Sheng"},
            {value:"吉林省", text:"吉林省 - Jilin Sheng"},
            {value:"江苏省", text:"江苏省 - Jiangsu Sheng"},
            {value:"江西省", text:"江西省 - Jiangxi Sheng"},
            {value:"辽宁省", text:"辽宁省 - Liaoning Sheng"},
            {value:"内蒙古自治区", text:"内蒙古 - Neimenggu Zizhiqu"},
            {value:"宁夏回族自治区", text:"宁夏 - Ningxia Huizuzizhiqu"},
            {value:"青海省", text:"青海省 - Qinghai Sheng"},
            {value:"山东省", text:"山东省 - Shandong Sheng"},
            {value:"山西省", text:"山西省 - Shanxi Sheng"},
            {value:"陕西省", text:"陕西省 - Shaanxi Sheng"},
            {value:"上海市", text:"上海市 - Shanghai Shi"},
            {value:"四川省", text:"四川省 - Sichuan Sheng"},
            {value:"台湾", text:"台湾 - Taiwan"},
            {value:"天津市", text:"天津市 - Tianjin Shi"},
            {value:"西藏自治区", text:"西藏 - Xizang Zizhiqu"},
            {value:"香港", text:"香港 - Hong Kong"},
            {value:"新疆维吾尔自治区", text:"新疆 - Xinjiang Weiwuerzizhiqu"},
            {value:"云南省", text:"云南省 - Yunnan Sheng"},
            {value:"浙江省", text:"浙江省 - Zhejiang Sheng"},
        ],
        AE: [
            {value:"أبو ظبي", text:"أبو ظبي - Abu Dhabi"},
            {value:"إمارة الشارقةّ", text:"الشارقة - Sharjah"},
            {value:"الفجيرة", text:"الفجيرة - Fujairah"},
            {value:"ام القيوين", text:"ام القيوين - Umm Al Quwain"},
            {value:"إمارة دبيّ", text:"دبي - Dubai"},
            {value:"إمارة رأس الخيمة", text:"رأس الخيمة - Ras al Khaimah"},
            {value:"عجمان", text:"عجمان - Ajman"},
        ],
        AU: [
            {value:"ACT", text:"Australian Capital Territory"},
            {value:"NSW", text:"New South Wales"},
            {value:"NT", text:"Northern Territory"},
            {value:"QLD", text:"Queensland"},
            {value:"SA", text:"South Australia"},
            {value:"TAS", text:"Tasmania"},
            {value:"VIC", text:"Victoria"},
            {value:"WA", text:"Western Australia"},
        ]
    }
}